[project]
name = "MLMC"
version = "0.1.0"
description = "machine learning on micro controller"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "ultralytics>=8.3.152",
  "imx500-converter[pt]>=3.16.1",
  "edge-mdt-tpc>=1.1.0",
  "edge-mdt-cl>=1.0.0",
  "polars>=1.31.0",
  "onnx>=1.16.1",
]
[project.optional-dependencies]
cpu = ["torch>=2.7.0", "torchvision>=0.22.0"]
cu128 = ["torch>=2.7.0", "torchvision>=0.22.0"]

[tool.uv]
conflicts = [[{ extra = "cpu" }, { extra = "cu128" }]]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
# uv sync --extra cpu
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
# uv sync --extra cu128
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
